### ISSUE TITLE
Landscape Mode is too big

### ISSUE THREAD

**Issue by RandomModderJDK** [SimpleMobileTools/Simple-Keyboard#81] opened 2022-08-16 02:02 UTC
Can you maybe add an option to change the height of the keyboard? I dont like the big buttons, because you can see nothing.

**Comment by dwettstein** [comment] 2023-01-02 16:44
Relates https://github.com/SimpleMobileTools/Simple-Keyboard/issues/45

**Comment by tibbi** [comment] 2023-08-31 20:25
duplicate of #45

**Closed by tibbi** 2023-08-31 20:25 UTC
Labels: feature request
