### ISSUE TITLE
Could you add the following:

### ISSUE THREAD

**Issue by NoBorderz** [SimpleMobileTools/Simple-Keyboard#106] opened 2022-11-11 11:03 UTC
Hi :)
Would it be possible to implement an option to add a row of numbers to the keyboard? 
Also on german keyboard I would love to have äöü just on the right side of the keyboard without having to click long on a letter..
Thanks a lot!! Also for all your other great work!

**Comment by tibbi** [comment] 2022-11-11 14:24
duplicate of #53

**Closed by tibbi** 2022-11-11 14:24 UTC
