### ISSUE TITLE
Turkish-Q language support

### ISSUE THREAD

**Issue by ondern** [SimpleMobileTools/Simple-Keyboard#76] opened 2022-08-07 03:01 UTC

**Comment by ondern** [comment] 2022-08-07 03:04
https://github.com/rkkr/simple-keyboard

This app provide Turkish-Q layout support. You can fork the code.

**Comment by Naveen3Singh** [comment] 2022-08-13 18:03
@ondern if you'd like to provide some feedback, [here's a test APK](https://github.com/Naveen3Singh/Simple-Keyboard/releases/download/test_release_turkish_q/keyboard-prepaid-debug.apk) with Turkish-Q support added.

_Apk is meant for testing only, pls uninstall afterward._

**Comment by ondern** [comment] 2022-08-13 21:13
Looks ok. It might be better if we can hide text panel set keyboard height and text bold

**Comment by ondern** [comment] 2022-08-13 21:15
Looks ok. It might be better if we can hide text panel set keyboard height and text bold

**Comment by ondern** [comment] 2022-08-13 21:22
Looks ok. It might be better if we can hide text panel set keyboard height and text bold

**Comment by suttod** [comment] 2022-12-28 09:03
Original request closed by #83 
Numpad request is duplicate of #93 and closed by #122

**Comment by tibbi** [comment] 2023-06-27 09:42
this has been added already

**Closed by tibbi** 2023-06-27 09:42 UTC
