### ISSUE TITLE
[Feature Request] Inline Autofill for Password Managers

### ISSUE THREAD

**Issue by devbytemehedi** [SimpleMobileTools/Simple-Keyboard#208] opened 2023-06-26 14:32 UTC
Is it possible to add support for inline autofill for password managers like Bitwarden?

I'm unsure whether or not this feature would require proprietary dependencies, or how difficult it would be to implement, but I hadn't seen it mentioned yet as a feature request. I use Bitwarden, and while the pop-up menu works fine, it would be nice if there was integration into the keyboard like Gboard had.

**Comment by tibbi** [comment] 2023-06-26 14:42
guess this is a duplicate of #199

**Closed by tibbi** 2023-06-26 14:42 UTC
